package cg.genealogie.orm.dao;

import cg.genealogie.orm.base.BaseNomDAO;

/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is the object class that relates to the nom table.
 * Any customizations belong here.
 */
public class NomDAO extends BaseNomDAO {
}