package cg.genealogie.orm.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the mariage table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="mariage"
 */
public abstract class BaseMariage  implements Serializable {

	public static String PROP_ID = "Id";
	public static String PROP_DATE_MARIAGE = "DateMariage";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private cg.genealogie.orm.MariagePK _id;

	// fields
	private java.util.Date _dateMariage;


	// constructors
	public BaseMariage () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseMariage (cg.genealogie.orm.MariagePK _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     */
	public cg.genealogie.orm.MariagePK getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (cg.genealogie.orm.MariagePK _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: dateMariage
	 */
	public java.util.Date getDateMariage () {
		return _dateMariage;
	}

	/**
	 * Set the value related to the column: dateMariage
	 * @param _dateMariage the dateMariage value
	 */
	public void setDateMariage (java.util.Date _dateMariage) {
		this._dateMariage = _dateMariage;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof cg.genealogie.orm.base.BaseMariage)) return false;
		else {
			cg.genealogie.orm.base.BaseMariage mObj = (cg.genealogie.orm.base.BaseMariage) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}