package cg.genealogie.orm.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the personne table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="personne"
 */
public abstract class BasePersonne  implements Serializable {

	public static String PROP_ID_PERSONNE = "IdPersonne";
	public static String PROP_IDPERSONNE2 = "Idpersonne2";
	public static String PROP_IDPERSONNE1 = "Idpersonne1";
	public static String PROP_NAISSANCE = "Naissance";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _idPersonne;

	// fields
	private java.util.Date _naissance;

	// many to one
	private cg.genealogie.orm.Personne _idpersonne2;
	private cg.genealogie.orm.Personne _idpersonne1;

	// collections
	private java.util.Set _personneSetByIdpersonne2;
	private java.util.Set _personneSetByIdpersonne1;
	private java.util.Set _mariageSetByIdpersonne1;
	private java.util.Set _mariageSetByIdPersonne;
	private java.util.Set _prenomSet;
	private java.util.Set _nomSet;


	// constructors
	public BasePersonne () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BasePersonne (java.lang.Integer _idPersonne) {
		this.setIdPersonne(_idPersonne);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BasePersonne (
		java.lang.Integer _idPersonne,
		cg.genealogie.orm.Personne _idpersonne2,
		cg.genealogie.orm.Personne _idpersonne1,
		java.util.Date _naissance) {

		this.setIdPersonne(_idPersonne);
		this.setIdpersonne2(_idpersonne2);
		this.setIdpersonne1(_idpersonne1);
		this.setNaissance(_naissance);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="idPersonne"
     */
	public java.lang.Integer getIdPersonne () {
		return _idPersonne;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idPersonne the new ID
	 */
	public void setIdPersonne (java.lang.Integer _idPersonne) {
		this._idPersonne = _idPersonne;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: naissance
	 */
	public java.util.Date getNaissance () {
		return _naissance;
	}

	/**
	 * Set the value related to the column: naissance
	 * @param _naissance the naissance value
	 */
	public void setNaissance (java.util.Date _naissance) {
		this._naissance = _naissance;
	}


	/**
     * @hibernate.property
     *  column=idPersonne_2
	 * not-null=true
	 */
	public cg.genealogie.orm.Personne getIdpersonne2 () {
		return this._idpersonne2;
	}

	/**
	 * Set the value related to the column: idPersonne_2
	 * @param _idpersonne2 the idPersonne_2 value
	 */
	public void setIdpersonne2 (cg.genealogie.orm.Personne _idpersonne2) {
		this._idpersonne2 = _idpersonne2;
	}


	/**
     * @hibernate.property
     *  column=idPersonne_1
	 * not-null=true
	 */
	public cg.genealogie.orm.Personne getIdpersonne1 () {
		return this._idpersonne1;
	}

	/**
	 * Set the value related to the column: idPersonne_1
	 * @param _idpersonne1 the idPersonne_1 value
	 */
	public void setIdpersonne1 (cg.genealogie.orm.Personne _idpersonne1) {
		this._idpersonne1 = _idpersonne1;
	}


	/**
	 * Return the value associated with the column: PersonneSetByIdpersonne2
	 */
	public java.util.Set getPersonneSetByIdpersonne2 () {
		return this._personneSetByIdpersonne2;
	}

	/**
	 * Set the value related to the column: PersonneSetByIdpersonne2
	 * @param _personneSetByIdpersonne2 the PersonneSetByIdpersonne2 value
	 */
	public void setPersonneSetByIdpersonne2 (java.util.Set _personneSetByIdpersonne2) {
		this._personneSetByIdpersonne2 = _personneSetByIdpersonne2;
	}
	
	public void addToPersonneSetByIdpersonne2 (Object obj) {
		if (null == this._personneSetByIdpersonne2) this._personneSetByIdpersonne2 = new java.util.HashSet();
		this._personneSetByIdpersonne2.add(obj);
	}



	/**
	 * Return the value associated with the column: PersonneSetByIdpersonne1
	 */
	public java.util.Set getPersonneSetByIdpersonne1 () {
		return this._personneSetByIdpersonne1;
	}

	/**
	 * Set the value related to the column: PersonneSetByIdpersonne1
	 * @param _personneSetByIdpersonne1 the PersonneSetByIdpersonne1 value
	 */
	public void setPersonneSetByIdpersonne1 (java.util.Set _personneSetByIdpersonne1) {
		this._personneSetByIdpersonne1 = _personneSetByIdpersonne1;
	}
	
	public void addToPersonneSetByIdpersonne1 (Object obj) {
		if (null == this._personneSetByIdpersonne1) this._personneSetByIdpersonne1 = new java.util.HashSet();
		this._personneSetByIdpersonne1.add(obj);
	}



	/**
	 * Return the value associated with the column: MariageSetByIdpersonne1
	 */
	public java.util.Set getMariageSetByIdpersonne1 () {
		return this._mariageSetByIdpersonne1;
	}

	/**
	 * Set the value related to the column: MariageSetByIdpersonne1
	 * @param _mariageSetByIdpersonne1 the MariageSetByIdpersonne1 value
	 */
	public void setMariageSetByIdpersonne1 (java.util.Set _mariageSetByIdpersonne1) {
		this._mariageSetByIdpersonne1 = _mariageSetByIdpersonne1;
	}
	
	public void addToMariageSetByIdpersonne1 (Object obj) {
		if (null == this._mariageSetByIdpersonne1) this._mariageSetByIdpersonne1 = new java.util.HashSet();
		this._mariageSetByIdpersonne1.add(obj);
	}



	/**
	 * Return the value associated with the column: MariageSetByIdPersonne
	 */
	public java.util.Set getMariageSetByIdPersonne () {
		return this._mariageSetByIdPersonne;
	}

	/**
	 * Set the value related to the column: MariageSetByIdPersonne
	 * @param _mariageSetByIdPersonne the MariageSetByIdPersonne value
	 */
	public void setMariageSetByIdPersonne (java.util.Set _mariageSetByIdPersonne) {
		this._mariageSetByIdPersonne = _mariageSetByIdPersonne;
	}
	
	public void addToMariageSetByIdPersonne (Object obj) {
		if (null == this._mariageSetByIdPersonne) this._mariageSetByIdPersonne = new java.util.HashSet();
		this._mariageSetByIdPersonne.add(obj);
	}



	/**
	 * Return the value associated with the column: PrenomSet
	 */
	public java.util.Set getPrenomSet () {
		return this._prenomSet;
	}

	/**
	 * Set the value related to the column: PrenomSet
	 * @param _prenomSet the PrenomSet value
	 */
	public void setPrenomSet (java.util.Set _prenomSet) {
		this._prenomSet = _prenomSet;
	}
	
	public void addToPrenomSet (Object obj) {
		if (null == this._prenomSet) this._prenomSet = new java.util.HashSet();
		this._prenomSet.add(obj);
	}



	/**
	 * Return the value associated with the column: NomSet
	 */
	public java.util.Set getNomSet () {
		return this._nomSet;
	}

	/**
	 * Set the value related to the column: NomSet
	 * @param _nomSet the NomSet value
	 */
	public void setNomSet (java.util.Set _nomSet) {
		this._nomSet = _nomSet;
	}
	
	public void addToNomSet (Object obj) {
		if (null == this._nomSet) this._nomSet = new java.util.HashSet();
		this._nomSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof cg.genealogie.orm.base.BasePersonne)) return false;
		else {
			cg.genealogie.orm.base.BasePersonne mObj = (cg.genealogie.orm.base.BasePersonne) obj;
			if (null == this.getIdPersonne() || null == mObj.getIdPersonne()) return false;
			else return (this.getIdPersonne().equals(mObj.getIdPersonne()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdPersonne()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdPersonne().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}