package cg.genealogie.orm.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the prenomme table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="prenomme"
 */
public abstract class BasePrenomme  implements Serializable {



	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private cg.genealogie.orm.Prenom _prenom;
	private cg.genealogie.orm.Personne _idPersonne;


	// constructors
	public BasePrenomme () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BasePrenomme (
		cg.genealogie.orm.Prenom _prenom,
		cg.genealogie.orm.Personne _idPersonne) {

		this.setPrenom(_prenom);
		this.setIdPersonne(_idPersonne);
		initialize();
	}

	protected void initialize () {}



	/**
     * @hibernate.property
     *  column=prenom
	 * not-null=true
	 */
	public cg.genealogie.orm.Prenom getPrenom () {
		return this._prenom;
	}

	/**
	 * Set the value related to the column: prenom
	 * @param _prenom the prenom value
	 */
	public void setPrenom (cg.genealogie.orm.Prenom _prenom) {
		this._prenom = _prenom;
		this.hashCode = Integer.MIN_VALUE;
	}

	/**
     * @hibernate.property
     *  column=idPersonne
	 * not-null=true
	 */
	public cg.genealogie.orm.Personne getIdPersonne () {
		return this._idPersonne;
	}

	/**
	 * Set the value related to the column: idPersonne
	 * @param _idPersonne the idPersonne value
	 */
	public void setIdPersonne (cg.genealogie.orm.Personne _idPersonne) {
		this._idPersonne = _idPersonne;
		this.hashCode = Integer.MIN_VALUE;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof cg.genealogie.orm.Prenomme)) return false;
		else {
			cg.genealogie.orm.Prenomme mObj = (cg.genealogie.orm.Prenomme) obj;
			if (null != this.getPrenom() && null != mObj.getPrenom()) {
				if (!this.getPrenom().equals(mObj.getPrenom())) {
					return false;
				}
			}
			else {
				return false;
			}
			if (null != this.getIdPersonne() && null != mObj.getIdPersonne()) {
				if (!this.getIdPersonne().equals(mObj.getIdPersonne())) {
					return false;
				}
			}
			else {
				return false;
			}
			return true;
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			StringBuffer sb = new StringBuffer();
			if (null != this.getPrenom()) {
				sb.append(this.getPrenom().hashCode());
				sb.append(":");
			}
			else {
				return super.hashCode();
			}
			if (null != this.getIdPersonne()) {
				sb.append(this.getIdPersonne().hashCode());
				sb.append(":");
			}
			else {
				return super.hashCode();
			}
			this.hashCode = sb.toString().hashCode();
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}