package cg.genealogie.orm.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the nomme table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="nomme"
 */
public abstract class BaseNomme  implements Serializable {



	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private cg.genealogie.orm.Nom _nom;
	private cg.genealogie.orm.Personne _idPersonne;


	// constructors
	public BaseNomme () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseNomme (
		cg.genealogie.orm.Nom _nom,
		cg.genealogie.orm.Personne _idPersonne) {

		this.setNom(_nom);
		this.setIdPersonne(_idPersonne);
		initialize();
	}

	protected void initialize () {}



	/**
     * @hibernate.property
     *  column=nom
	 * not-null=true
	 */
	public cg.genealogie.orm.Nom getNom () {
		return this._nom;
	}

	/**
	 * Set the value related to the column: nom
	 * @param _nom the nom value
	 */
	public void setNom (cg.genealogie.orm.Nom _nom) {
		this._nom = _nom;
		this.hashCode = Integer.MIN_VALUE;
	}

	/**
     * @hibernate.property
     *  column=idPersonne
	 * not-null=true
	 */
	public cg.genealogie.orm.Personne getIdPersonne () {
		return this._idPersonne;
	}

	/**
	 * Set the value related to the column: idPersonne
	 * @param _idPersonne the idPersonne value
	 */
	public void setIdPersonne (cg.genealogie.orm.Personne _idPersonne) {
		this._idPersonne = _idPersonne;
		this.hashCode = Integer.MIN_VALUE;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof cg.genealogie.orm.Nomme)) return false;
		else {
			cg.genealogie.orm.Nomme mObj = (cg.genealogie.orm.Nomme) obj;
			if (null != this.getNom() && null != mObj.getNom()) {
				if (!this.getNom().equals(mObj.getNom())) {
					return false;
				}
			}
			else {
				return false;
			}
			if (null != this.getIdPersonne() && null != mObj.getIdPersonne()) {
				if (!this.getIdPersonne().equals(mObj.getIdPersonne())) {
					return false;
				}
			}
			else {
				return false;
			}
			return true;
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			StringBuffer sb = new StringBuffer();
			if (null != this.getNom()) {
				sb.append(this.getNom().hashCode());
				sb.append(":");
			}
			else {
				return super.hashCode();
			}
			if (null != this.getIdPersonne()) {
				sb.append(this.getIdPersonne().hashCode());
				sb.append(":");
			}
			else {
				return super.hashCode();
			}
			this.hashCode = sb.toString().hashCode();
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}