package cg.genealogie.orm.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the prenom table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="prenom"
 */
public abstract class BasePrenom  implements Serializable {

	public static String PROP_PRENOM = "Prenom";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.String _prenom;

	// collections
	private java.util.Set _personneSet;


	// constructors
	public BasePrenom () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BasePrenom (java.lang.String _prenom) {
		this.setPrenom(_prenom);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="prenom"
     */
	public java.lang.String getPrenom () {
		return _prenom;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _prenom the new ID
	 */
	public void setPrenom (java.lang.String _prenom) {
		this._prenom = _prenom;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: PersonneSet
	 */
	public java.util.Set getPersonneSet () {
		return this._personneSet;
	}

	/**
	 * Set the value related to the column: PersonneSet
	 * @param _personneSet the PersonneSet value
	 */
	public void setPersonneSet (java.util.Set _personneSet) {
		this._personneSet = _personneSet;
	}
	
	public void addToPersonneSet (Object obj) {
		if (null == this._personneSet) this._personneSet = new java.util.HashSet();
		this._personneSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof cg.genealogie.orm.base.BasePrenom)) return false;
		else {
			cg.genealogie.orm.base.BasePrenom mObj = (cg.genealogie.orm.base.BasePrenom) obj;
			if (null == this.getPrenom() || null == mObj.getPrenom()) return false;
			else return (this.getPrenom().equals(mObj.getPrenom()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getPrenom()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getPrenom().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}