package cg.genealogie.orm.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the nom table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="nom"
 */
public abstract class BaseNom  implements Serializable {

	public static String PROP_NOM = "Nom";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.String _nom;

	// collections
	private java.util.Set _personneSet;


	// constructors
	public BaseNom () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseNom (java.lang.String _nom) {
		this.setNom(_nom);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="nom"
     */
	public java.lang.String getNom () {
		return _nom;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _nom the new ID
	 */
	public void setNom (java.lang.String _nom) {
		this._nom = _nom;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: PersonneSet
	 */
	public java.util.Set getPersonneSet () {
		return this._personneSet;
	}

	/**
	 * Set the value related to the column: PersonneSet
	 * @param _personneSet the PersonneSet value
	 */
	public void setPersonneSet (java.util.Set _personneSet) {
		this._personneSet = _personneSet;
	}
	
	public void addToPersonneSet (Object obj) {
		if (null == this._personneSet) this._personneSet = new java.util.HashSet();
		this._personneSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof cg.genealogie.orm.base.BaseNom)) return false;
		else {
			cg.genealogie.orm.base.BaseNom mObj = (cg.genealogie.orm.base.BaseNom) obj;
			if (null == this.getNom() || null == mObj.getNom()) return false;
			else return (this.getNom().equals(mObj.getNom()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getNom()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getNom().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}